version: '3.7'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/restaurant
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://backend:5000

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
